### ISSUE TITLE
Support embedded elisp in template files

### ISSUE THREAD

**Issue by chrisbarrett** [chrisbarrett/skeletor.el#2]
Add support for evaluating elisp expressions and inserting their results in template files. This would be particularly useful for transforming the case of replacements.

The template syntax for this might look like:

```
__(expression)__
```

**Comment by MassimoLauria** [comment]
How do we access to the expansion data?

If I use `__(upcase "__TITLE__")__` where `__TITLE__` is substituted with "Smashing stacks..." then
I would get "Smashing stacks..." instead of "SMASHING STACKS...", because of the order of the substitution/evaluation. 

What is the correct way? I need to be able to access the value which is going to be associated with `__TITLE__` already in my code.

**Comment by chrisbarrett** [comment]
Substitutions are not currently recursive, so it's not possible. I'll open a ticket on that.
